#!/bin/sh
# Written by Furey.
# With additions from Tony and Alander.
# cd /home/local/hdogan/Backup/Husky/HuskyBBS-Onceki/lib
# cd /home/staff/hidayet/HuskyBBS-Onceki/lib
# Set the port number.
port=3000
if [ "$1" != "" ]; then
    port="$1"
fi

# Change to area directory.
#cd ../lib

# Set limits.
if [ -e "shutdown.txt" ]; then
rm -f shutdown.txt
fi

while sleep 15; do
    # If you want to have logs in a different directory,
    #   change the 'set logfile' line to reflect the directory name.
    index=1000
    while true; do
	logfile="log/$index.log"
	if [ ! -e "$logfile" ]; then
	    break
	fi
	$((index++))
    done

    # Run rom.
    bbs $port >&! $logfile


    # Restart, giving old connections a chance to die.
    if [ -e "shutdown.txt" ]; then
	rm -f shutdown.txt
	exit 0
    fi
done
